#! /usr/bin/env ruby

# frozen_string_literal: true

require 'pry-nav'

wd = File.expand_path('..', File.dirname(__FILE__))
matrix = File.readlines("#{wd}/src/matrix.txt", chomp: true).map do |line|
  line.split('')
end

# filled in space is 0x20, empty is 0xA0

LEFT_PAD = 8
TOP_PAD = 1

hex_chars = [['0x20'] * (matrix.first.length + LEFT_PAD)] * TOP_PAD + matrix.map do |row|
  ['0x20'] * LEFT_PAD + row.map { _1 == '1' ? '0xA0' : '0x20' }
end.flatten

content = <<~CONTENT
  #include <stdint.h>
  #include <stddef.h>

  uint8_t rom[] = {
    #{hex_chars.join(', ')}
  };

  size_t matrix_width = #{matrix.length + LEFT_PAD};
  size_t matrix_height = #{matrix.length + TOP_PAD};
CONTENT

File.open("#{wd}/src/qr_rom.c", 'w+') do |f|
  f.puts content
end
